use_frameworks!

platform :ios, '8.0'

target 'LCPagingMenuView_Example' do
  pod 'LCPagingMenuView', :path => '../'

  target 'LCPagingMenuView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
